/* Existing Sprint 1 sprite rendering and effects, retained. */
const base='Assets/BRODUNArt/';
const actorAssets=new Map(BRODUN_ASSETS.assets.filter(a=>a.frames).map(a=>[a.file.split('/').pop().replace('.png',''),a]));
for(const asset of BRODUN_ADDON_ASSETS.assets.filter(a=>a.frames))actorAssets.set(asset.id,asset);
const ctx=document.getElementById('actors').getContext('2d');ctx.imageSmoothingEnabled=false;
const cache={};let effect=null;
function image(src){if(!cache[src]){cache[src]=new Image();cache[src].src=base+src;}return cache[src];}
for(const a of BRODUN_ASSETS.assets){image(a.file);for(const f of a.frames||[])image(f.file);}
function frameAt(name,motion,elapsed){const asset=actorAssets.get(name),animations=asset?.id?BRODUN_ADDON_ASSETS.animations:BRODUN_ASSETS.animations,anim=animations.find(a=>a.name===motion);if(!asset||!anim)return null;const n=Math.floor(Math.max(0,elapsed)*anim.fps/1000),idx=anim.loop?n%anim.frames:Math.min(anim.frames-1,n);return asset.frames.find(f=>f.name===motion+'_'+String(idx).padStart(2,'0'));}
function drawActor(name,motion,x,y,at,now){const asset=actorAssets.get(name),frame=frameAt(name,motion,now-at);if(!frame)return;const im=image(frame.file),def=B.Enemies[name],scale=def?def.display_height/Math.max(...asset.frames.map(f=>f.height)):.78;if(im.complete&&im.naturalWidth)ctx.drawImage(im,x-frame.pivotX*frame.width*scale,y-frame.height*scale,frame.width*scale,frame.height*scale);}
function drawEffect(now){if(!effect)return;const p=Math.min(1,(now-effect.start)/effect.duration),sx=390,sy=320,ex=830,ey=315,impact=p>.72;if(effect.kind==='guard'){ctx.save();ctx.globalAlpha=1-p*.6;ctx.strokeStyle=effect.type==='ice'?'#9ceaff':'#e3c276';ctx.lineWidth=8;ctx.beginPath();ctx.arc(330,310,52+p*45,Math.PI*.15,Math.PI*1.85);ctx.stroke();ctx.restore();return}ctx.save();ctx.globalCompositeOperation='lighter';if(effect.type==='lightning'){ctx.strokeStyle='#bff5ff';ctx.lineWidth=8;ctx.beginPath();ctx.moveTo(ex,80);for(let i=1;i<=8;i++)ctx.lineTo(ex+(i%2?25:-20),80+i*30*p);ctx.stroke()}else if(effect.type==='wind'){ctx.strokeStyle='#b7fff1';ctx.lineWidth=10;for(let i=0;i<3;i++){ctx.beginPath();ctx.arc(sx+(ex-sx)*p,ey,(35+i*16)*(1-p*.25),-.9,.9);ctx.stroke()}}else{const x=sx+(ex-sx)*p,y=sy+Math.sin(p*Math.PI)*-65;ctx.fillStyle=effect.type==='fire'?'#ff9e35':effect.type==='water'?'#6ee7ff':'#d8a95f';for(let i=0;i<5;i++){ctx.globalAlpha=1-i*.15;ctx.beginPath();ctx.arc(x-i*15,y+Math.sin(i)*5,18-i*2,0,Math.PI*2);ctx.fill()}}if(impact){ctx.globalAlpha=(1-p)*3;ctx.strokeStyle='#fff1ba';ctx.lineWidth=8;ctx.beginPath();ctx.arc(ex,ey,25+(p-.72)*250,0,Math.PI*2);ctx.stroke()}ctx.restore()}

const motions={hero:{name:'idle',at:0},enemy:{name:'idle',at:0}};
function setMotion(side,name){motions[side]={name,at:performance.now()};}
function tick(now){ctx.clearRect(0,0,1200,675);const r=B.Flow.run,b=B.Flow.battle;if(r&&b&&['battle','reward','defeat'].includes(B.Flow.screen)){const y=B.AreaData[r.area_index-1].floor_y;drawActor(r.character_id,motions.hero.name,285,y,motions.hero.at,now);drawActor(b.sprite,motions.enemy.name,925,y,motions.enemy.at,now);drawEffect(now);}if(B.Flow.screen==='gallery')document.querySelectorAll('.animated-enemy').forEach(img=>{const frame=frameAt(img.dataset.actor,img.dataset.motion||'idle',now-Number(img.dataset.at||0));if(frame&&img.dataset.frame!==frame.file){img.dataset.frame=frame.file;img.src=base+frame.file;}});requestAnimationFrame(tick);}
B.Art={image,setMotion,frameAt,prepare(name){const asset=actorAssets.get(name);if(asset)for(const frame of asset.frames)image(frame.file);},snapshot(){return {motions:structuredClone(motions),enemy_frame:B.Flow.battle?frameAt(B.Flow.battle.sprite,motions.enemy.name,performance.now()-motions.enemy.at)?.name:null};},playEffect(element,kind){effect={type:element,kind,start:performance.now(),duration:650};},clear(){effect=null;setMotion('hero','idle');setMotion('enemy','idle');}};
requestAnimationFrame(tick);
