/* RoomNode graph: start is outside the PRD's 10 room count. */
B.Dungeon={
 generate(seed){const middle=B.Shuffle(['battle','puzzle','event','battle','puzzle','event'],B.Rng(seed));const rows=[[['start','start',50]], [['r1','battle',50]], [['r2',middle[0],20],['r3',middle[1],50],['r4',middle[2],80]], [['r5',middle[3],20],['r6',middle[4],50],['r7',middle[5],80]], [['r8','battle',32],['r9','battle',68]], [['boss','boss',50]]];const nodes=rows.flatMap((row,col)=>row.map(([id,type,y])=>({id,room_type:type,column:col,x:7+col*17.2,y,floor_index:col<2?1:col<4?2:3,next_room_ids:[]})));const byId=Object.fromEntries(nodes.map(n=>[n.id,n]));byId.start.next_room_ids=['r1'];byId.r1.next_room_ids=['r2','r3','r4'];byId.r2.next_room_ids=['r5','r6'];byId.r3.next_room_ids=['r5','r6','r7'];byId.r4.next_room_ids=['r6','r7'];byId.r5.next_room_ids=['r8'];byId.r6.next_room_ids=['r8','r9'];byId.r7.next_room_ids=['r9'];byId.r8.next_room_ids=['boss'];byId.r9.next_room_ids=['boss'];return nodes;},
 decorate(nodes,seed){const rng=B.Rng(seed+5801);for(const n of nodes){if(n.room_type==='battle')n.encounter_type=n.id==='r9'?'elite':'normal';if(n.room_type==='event')n.event_kind=['shop','altar','rest_site'][Math.floor(rng()*3)];}return nodes;},
 node(run,id){return run.map.find(n=>n.id===id);},
 available(run){if(run.status!=='in_progress'||run.active_room_id)return [];const n=this.node(run,run.current_room_id);return n.next_room_ids.filter(id=>!run.completed_room_ids.includes(id));},
 enter(run,id){if(!this.available(run).includes(id))return null;const node=this.node(run,id);run.current_room_id=id;run.active_room_id=id;run.floor_index=node.floor_index;return node;},
 complete(run){const id=run.active_room_id;if(!id)return false;if(!run.completed_room_ids.includes(id))run.completed_room_ids.push(id);run.active_room_id=null;if(id==='boss')run.status='complete';return true;}
};
