/* UI only projects state. It cannot grant rewards or advance rooms. */
B.UI={
 overlay:document.getElementById('overlay'),
 reset(screen){const gallery=screen==='gallery';document.getElementById('stage').hidden=gallery;document.getElementById('stage').querySelectorAll('.damage-pop').forEach(el=>el.remove());document.getElementById('gallery').hidden=!gallery;this.overlay.className='overlay '+screen+'-screen';this.overlay.replaceChildren();const r=B.Flow.run,room=r?.active_room_id?B.Dungeon.node(r,r.active_room_id):null;const background=['title','select'].includes(screen)?'Backgrounds/title_background.png':screen==='event'&&room?.event_kind?B.EventKinds[room.event_kind].background:B.AreaData[(r?.area_index||1)-1].background;document.getElementById('bg').src='Assets/BRODUNArt/'+background;this.hud();},
 hud(){const r=B.Flow.run;document.getElementById('runHud').textContent=r?`${B.Heroes[r.character_id].name} · HP ${r.player.hp}/${r.player.max_hp} · Gold: ${r.player.gold} · 덱 ${r.deck.length}장`:'';document.getElementById('deckBtn').disabled=!r;document.getElementById('galleryBtn').disabled=!['title','select','map','gallery','complete','defeat'].includes(B.Flow.screen);},
 button(label,action,className='screen-btn'){const el=document.createElement('button');el.type='button';el.className=className;el.textContent=label;el.onclick=action;return el;},
 render(){const s=B.Flow.screen;this.reset(s);if(s==='title')this.title();else if(s==='select')this.select();else if(s==='map')this.map();else if(s==='battle')this.renderBattle();else if(s==='reward')this.reward();else if(s==='puzzle')this.puzzle();else if(s==='event')this.event();else if(s==='gallery')this.gallery();else this.result(s);},
 title(){this.overlay.innerHTML='<h1 class="logo">BRODUN</h1><p class="subtitle">BRANCH · BATTLE · BUILD</p><div class="menu"></div><div class="version">Sprint 5 · 던전과 덱 성장 프로토타입</div>';this.overlay.querySelector('.menu').append(this.button('게임 시작',()=>B.Flow.show('select')));},
 select(){this.overlay.innerHTML='<h2>캐릭터 선택</h2><p>캐릭터를 선택한 뒤 던전 맵에서 첫 방을 고르세요.</p><div class="hero-grid"></div>'+(B.Debug.enabled?'<label class="seed-input">DEBUG · 시드 <input id="seed" type="number" min="0" max="4294967295" value="'+B.Flow.seed+'" aria-label="던전 시드"></label>':'');
  for(const [id,h] of Object.entries(B.Heroes)){const btn=this.button('',()=>{B.Flow.selected=id;this.overlay.querySelectorAll('.hero-choice').forEach(e=>e.classList.toggle('selected',e.dataset.hero===id));},'hero-choice'+(B.Flow.selected===id?' selected':''));btn.dataset.hero=id;btn.innerHTML=`<img src="Assets/BRODUNArt/Frames/${id}/idle_00.png" alt=""><b>${h.name}</b><span>${h.desc}</span>`;this.overlay.querySelector('.hero-grid').append(btn);}
  const begin=this.button('선택 완료 · 던전으로',()=>{const field=document.getElementById('seed'),input=field?Number(field.value):B.Flow.seed;if(!Number.isInteger(input)||input<0||input>4294967295){field?.reportValidity();return;}B.Flow.start(B.Flow.selected,input);},'screen-btn select-go');begin.id='begin';this.overlay.append(begin);
 },
 roomName(n){return n.room_type==='start'?'시작':n.room_type==='boss'?'보스':n.room_type==='battle'?(n.encounter_type==='elite'?'엘리트 전투':'일반 전투'):n.room_type==='puzzle'?'퍼즐':B.EventKinds[n.event_kind]?.name||'이벤트';},
 roomIcon(n){return n.room_type==='event'?B.EventKinds[n.event_kind]?.icon:B.MapArt.icons[n.room_type];},
 map(){const r=B.Flow.run,available=B.Dungeon.available(r),current=B.Dungeon.node(r,r.current_room_id);
  this.overlay.innerHTML='<div class="maphead"><div>'+B.AreaData[r.area_index-1].name+' · '+r.floor_index+'층 / 3층'+(B.Debug.enabled?' <small>DEBUG · 시드 '+r.seed+'</small>':'')+'</div><div>HP '+r.player.hp+'/'+r.player.max_hp+' &nbsp; Gold: '+r.player.gold+' &nbsp; 덱 '+r.deck.length+'장</div></div><div class="map-instruction">연결된 다음 방을 선택하세요. <span>엘리트는 ★ 표시 · 밝은 방만 이동 가능</span></div><div class="mapnodes"><svg viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true"></svg></div><div class="next-room-strip"><h3>다음 방 선택</h3><div class="room-choices"></div></div><div class="map-legend"><span class="legend current">● 현재 위치</span><span class="legend available">○ 이동 가능</span><span class="legend locked">○ 이동 불가</span><span class="legend done">✓ 완료</span><span class="legend boss">◆ 보스</span></div>';
  const container=this.overlay.querySelector('.mapnodes'),svg=container.querySelector('svg');
  for(const n of r.map){for(const next of n.next_room_ids){const m=B.Dungeon.node(r,next),line=document.createElementNS('http://www.w3.org/2000/svg','line');for(const [key,value]of Object.entries({x1:n.x,y1:n.y,x2:m.x,y2:m.y}))line.setAttribute(key,value);line.classList.toggle('traversed',r.completed_room_ids.includes(next));svg.append(line);}
   const done=r.completed_room_ids.includes(n.id),here=current.id===n.id,can=available.includes(n.id),icon=this.roomIcon(n);
   const btn=this.button('',()=>B.Flow.enter(n.id),'node '+(done?'done ':'')+(here?'current ':'')+(can?'available ':'locked ')+(n.room_type==='boss'?'boss':''));btn.style.left=n.x+'%';btn.style.top=n.y+'%';btn.dataset.node=n.id;btn.disabled=!can;btn.setAttribute('aria-label',this.roomName(n)+' '+n.id+' · '+(here?'현재 위치 · ':'')+(done?'완료':can?'이동 가능':'이동 불가'));if(here)btn.setAttribute('aria-current','step');btn.innerHTML=(done?'<strong>✓</strong>':icon?'<img src="Assets/BRODUNArt/'+icon+'" alt="">':'<strong>▶</strong>')+'<em>'+(n.encounter_type==='elite'?'★ ':'')+this.roomName(n)+(here?' · 현재':'')+'</em>';container.append(btn);
  }
  const ids=[current.id,...available];if(!ids.includes('boss'))ids.push('boss');
  for(const id of ids){const n=B.Dungeon.node(r,id),here=id===current.id,can=available.includes(id),icon=this.roomIcon(n);const btn=this.button('',()=>B.Flow.enter(id),'room-choice '+(here?'selected':can?'normal':'locked'));btn.dataset.choice=id;btn.disabled=!can;
   for(const [state,file]of Object.entries(B.MapArt.states))btn.style.setProperty('--choice-'+state,'url("Assets/BRODUNArt/'+file+'")');
   btn.innerHTML='<div class="choice-icon">'+(icon?'<img src="Assets/BRODUNArt/'+icon+'" alt="">':'<strong>▶</strong>')+'</div><b>'+this.roomName(n)+'</b><small>'+(here?'현재 위치':can?(n.encounter_type==='elite'?'위험 높음':'이동 가능'):'이동 불가')+'</small>';btn.setAttribute('aria-label',this.roomName(n)+' · '+(here?'현재 위치':can?'이동 가능':'이동 불가'));this.overlay.querySelector('.room-choices').append(btn);
  }
  if(B.Flow.feedback){const message=B.Flow.feedback;B.Flow.feedback=null;this.toast(message);}
 },
 card(def,action,className='battle-card'){const btn=this.button('',action,className);btn.dataset.card=def.id;const guard=def.effects.some(e=>e.type==='block')&&!def.effects.some(e=>e.type==='damage');if(guard)btn.classList.add('guard');btn.innerHTML=`<span class="cost">${def.cost}</span><img src="Assets/BRODUNArt/Frames/ui_icons/${def.element}.png" alt=""><b>${def.name}</b><small>${B.Elements[def.element]}</small><p>${def.description}</p>`;btn.setAttribute('aria-label',`${def.name}, 비용 ${def.cost}, ${def.description}`);return btn;},
 renderBattle(){if(B.Flow.screen!=='battle')return;const r=B.Flow.run,b=B.Flow.battle,e=b.enemy,intent=b.phase==='enemy'?b.executing_intent:B.Enemy.preview(b),p=B.IntentPresentation[intent.type];
  const changed=this.lastBattle===b&&this.lastEnergy!==b.energy?(b.energy>this.lastEnergy?'gain':'spend'):'';this.lastBattle=b;this.lastEnergy=b.energy;this.hud();
  const intentText=intent.type==='attack'?intent.amount+(intent.hits>1?' × '+intent.hits:''):intent.type==='block'?String(intent.amount):'+'+intent.amount;
  const forecastBlock=b.phase==='enemy'?b.executing_block:b.block,tooltip=B.Enemy.describe(intent,forecastBlock);
  this.overlay.innerHTML='<div class="hud"><div class="unit-status"><div class="unit-name">'+B.Heroes[r.character_id].name+' · Gold: '+r.player.gold+'</div><div class="bar hero"><i style="width:'+r.player.hp/r.player.max_hp*100+'%"></i></div><span class="numbers">HP '+r.player.hp+'/'+r.player.max_hp+' · 방어 '+b.block+' · 힘 '+b.strength+'</span></div><div class="battle-turn">'+(b.status==='won'?'승리 · 보상 준비':b.phase==='enemy'?'적 행동 중':'플레이어 턴 '+b.turn)+'</div><div class="unit-status enemy"><div class="unit-name">'+({normal:'일반',elite:'엘리트',boss:'보스'}[b.rank])+' · '+b.name+'</div><div class="bar"><i style="width:'+e.hp/e.max_hp*100+'%"></i></div><span class="numbers">HP '+e.hp+'/'+e.max_hp+' · 방어 '+e.block+' · 힘 '+e.strength+'</span><div class="enemy-status">독 '+e.poison+' · 약화 '+e.weak+'턴 · 속성 '+(B.Elements[e.element]||'없음')+'</div></div></div><div id="enemyIntent" class="enemy-intent '+intent.type+'" tabindex="0" title="'+tooltip+'" role="img" aria-label="'+tooltip+'" data-type="'+intent.type+'" data-amount="'+intent.amount+'" data-hits="'+intent.hits+'"><span class="intent-icon">'+(p.icon?'<img src="Assets/BRODUNArt/'+p.icon+'" alt="">':p.symbol)+'</span><div><small>다음 행동 · '+p.label+'</small><strong>'+intentText+'</strong><span>'+(intent.type==='attack'?'방어 후 HP 피해 '+Math.max(0,intent.amount*intent.hits-forecastBlock):intent.type==='block'?'적 방어도 획득':'이후 공격 강화')+'</span></div></div><div class="battle-log" aria-live="polite">'+b.log.slice(-2).map(message=>'<div>'+message+'</div>').join('')+'</div><div class="turn-controls"></div><div class="hand"></div><div id="energyPanel" class="energy-panel '+changed+'" aria-live="polite"><span>행동력 · ENERGY</span><strong>'+b.energy+' <small>/ '+b.max_energy+'</small></strong><div class="energy-pips">'+Array.from({length:Math.max(b.max_energy,b.energy)},(_,i)=>'<i class="'+(i<b.energy?'filled':'')+'"></i>').join('')+'</div><small>턴 기본 '+b.max_energy+' · 임시 상한 '+B.Config.energy_cap+'</small></div><div class="piles">덱 '+b.piles.draw.length+' · 버림 '+b.piles.discard.length+' · 소멸 '+b.piles.exhaust.length+'</div>';
  const end=this.button(b.busy?'처리 중…':'턴 종료',()=>B.Battle.endTurn());end.id='endTurn';end.disabled=b.busy||b.status!=='active';this.overlay.querySelector('.turn-controls').append(end);
  for(const instance of b.piles.hand){const def=B.CardById[instance.card_id],btn=this.card(def,()=>B.Battle.play(instance.instance_id));btn.dataset.instance=instance.instance_id;btn.disabled=b.busy||b.status!=='active'||b.energy<def.cost;this.overlay.querySelector('.hand').append(btn);}
 },
 panel(title,description){this.overlay.innerHTML=`<section class="panel"><h2>${title}</h2><p>${description}</p><div class="panel-body"></div></section>`;return this.overlay.querySelector('.panel-body');},
 reward(){const pending=B.Flow.reward;if(!pending||pending.resolved)return;const body=this.panel('전투 승리 · 보상',`보상 하나를 선택하거나 건너뛰세요. 보상 처리가 끝나야 맵으로 돌아갑니다.<br>Gold: ${B.Flow.run.player.gold} · 현재 덱 ${B.Flow.run.deck.length}장`);body.className='panel-body reward-body';
  if(pending.mode==='choice'){const gold=this.button('골드 +'+pending.gold,()=>B.Flow.resolveReward('gold'),'screen-btn reward-option'),icon=document.createElement('img');icon.src='Assets/BRODUNArt/'+B.MapArt.icons.gold;icon.alt='';gold.prepend(icon);body.append(gold,this.button('새 카드 획득 · 3장 중 선택',()=>{pending.mode='cards';this.render();},'screen-btn reward-option'));}
  else{const choices=document.createElement('div');choices.className='card-candidates';for(const id of pending.candidates)choices.append(this.card(B.CardById[id],()=>B.Flow.resolveReward('card',id)));body.append(choices);body.append(this.button('보상 종류로 돌아가기',()=>{pending.mode='choice';this.render();}));}
  const skip=this.button('Skip · 보상 건너뛰기',()=>B.Flow.resolveReward('skip'));skip.id='skipReward';body.append(skip);
 },
 puzzle(){const body=this.panel('퍼즐방 · 속성 봉인','표식 순서대로 봉인을 누르세요: 땅 → 물 → 불<br>성공하면 보상 하나를 받습니다. (Sprint 5 임시 콘텐츠)');let index=0;const seq=['earth','water','fire'],message=document.createElement('p');message.id='puzzleProgress';message.textContent='0 / 3';for(const element of ['water','fire','earth'])body.append(this.button(B.Elements[element],()=>{if(seq[index]===element){index++;message.textContent=index+' / 3';if(index===3)B.Flow.finishPuzzle();}else{index=0;message.textContent='다시 시도 · 0 / 3';}}));body.append(message,this.button('퍼즐 건너뛰기 · 보상 없음',()=>B.Flow.finishRoom('퍼즐을 건너뛰었습니다.')));},
 event(){const room=B.Dungeon.node(B.Flow.run,B.Flow.run.active_room_id),kind=B.EventKinds[room.event_kind];const body=this.panel('이벤트방 · '+kind.name,'새 배경을 적용한 임시 이벤트입니다. 구매·강화·제단 위험 선택은 아직 없으며, 아래 선택으로 기존 이벤트 흐름만 검증합니다.');body.append(this.button('휴식 · HP +'+B.Config.event.heal,()=>B.Flow.eventChoice('heal')),this.button('주머니 줍기 · Gold +'+B.Config.event.gold,()=>B.Flow.eventChoice('gold')));},
 result(screen){const complete=screen==='complete',body=this.panel(complete?'던전 돌파':'게임 오버',complete?`보스 보상까지 완료했습니다!<br>Gold: ${B.Flow.run.player.gold} · 덱 ${B.Flow.run.deck.length}장`:'HP가 0이 되어 이번 도전이 끝났습니다.');body.append(this.button('다시 시작 · 캐릭터 선택',()=>B.Flow.newRun()));if(B.Flow.feedback){const message=B.Flow.feedback;B.Flow.feedback=null;this.toast(message);}},
 toast(message){const el=document.createElement('div');el.className='toast';el.setAttribute('role','status');el.textContent=message;this.overlay.append(el);setTimeout(()=>el.remove(),2600);},
 pop(text,side){const el=document.createElement('div');el.className='damage-pop';el.textContent=text;el.style.left=side==='hero'?'24%':'74%';el.style.top='38%';document.getElementById('stage').append(el);setTimeout(()=>el.remove(),1000);},
 deck(){const dialog=document.getElementById('deckDialog'),r=B.Flow.run;if(!r)return;dialog.innerHTML=`<h2 id="deckTitle">현재 덱 · ${r.deck.length}장</h2><p>전투 사이에도 유지되는 덱입니다. ★ 표시는 보상으로 획득한 카드입니다.</p><div class="deck-list"></div>`;for(const instance of r.deck){const def=B.CardById[instance.card_id],item=document.createElement('article');item.dataset.card=def.id;item.dataset.instance=instance.instance_id;item.innerHTML=`<h3>${r.acquired_cards.includes(instance.instance_id)?'★ ':''}${def.name} <small>비용 ${def.cost} · ${B.Elements[def.element]}</small></h3><p>${def.description}</p>`;dialog.querySelector('.deck-list').append(item);}dialog.append(this.button('닫기',()=>dialog.close()));if(!dialog.open)dialog.showModal();},
 gallery(){const gallery=document.getElementById('gallery');gallery.replaceChildren();gallery.append(this.button('게임 화면으로 돌아가기',()=>B.Flow.show(B.Flow.galleryReturn||'title')));
  for(const def of Object.values(B.Enemies).filter(d=>BRODUN_ADDON_ASSETS.assets.some(a=>a.id===d.id))){B.Art.prepare(def.id);const tile=document.createElement('article');tile.className='tile animation-tile';tile.innerHTML='<h3>'+def.name+' · '+def.id+'</h3><img class="animated-enemy" data-actor="'+def.id+'" data-motion="idle" data-at="'+performance.now()+'" src="Assets/BRODUNArt/'+B.Art.frameAt(def.id,'idle',0).file+'" alt="'+def.name+'"><div class="animation-controls"></div>';for(const motion of BRODUN_ADDON_ASSETS.animations)tile.querySelector('.animation-controls').append(this.button(motion.name,()=>{const img=tile.querySelector('img');img.dataset.motion=motion.name;img.dataset.at=performance.now();}));gallery.append(tile);}
  for(const asset of [...BRODUN_ASSETS.assets,...BRODUN_ADDON_ASSETS.assets.filter(a=>!a.frames)]){const tile=document.createElement('article');tile.className='tile';const title=document.createElement('h3');title.textContent=asset.file;const img=document.createElement('img');img.src='Assets/BRODUNArt/'+asset.file;img.alt=asset.file;tile.append(title,img);gallery.append(tile);}
 }
};
