/* Run with Node + Playwright. No debug combat mutations: actions use actual UI. */
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict'),cp=require('node:child_process');
const {chromium}=require('playwright'),root=path.resolve(__dirname,'..');
const out=process.env.BRODUN_QA_OUTPUT||path.join(root,'test-output');fs.mkdirSync(out,{recursive:true});
const baseline=cp.execFileSync('git',['show','b60eb7f:index.html'],{cwd:root,encoding:'utf8'});
const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.svg':'image/svg+xml','.json':'application/json'};
const server=http.createServer((req,res)=>{const pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname);if(pathname==='/__baseline'){res.setHeader('Content-Type','text/html; charset=utf-8');res.end(baseline);return;}const file=path.resolve(root,'.'+(pathname==='/'?'/index.html':pathname));if(!file.startsWith(root+path.sep)){res.writeHead(403);res.end();return;}fs.readFile(file,(err,data)=>{if(err){res.writeHead(404);res.end();return;}res.setHeader('Content-Type',(mime[path.extname(file)]||'text/plain')+'; charset=utf-8');res.end(data);});});
const results=[],errors=[],failures=[];let browser,page;
async function record(name,fn){await fn();results.push(name);console.log('PASS '+name);}
async function screen(value){await page.waitForFunction(value=>B.Flow.screen===value,value);}
async function start(hero='warrior',seed=17){await page.locator('#newRun').click();await page.locator('[data-hero="'+hero+'"]').click();await page.locator('#seed').fill(String(seed));await page.locator('#begin').click();await screen('map');}
async function win(){await screen('battle');for(let step=0;step<65;step++){await page.waitForFunction(()=>B.Flow.screen!=='battle'||!B.Flow.battle.busy);if(await page.evaluate(()=>B.Flow.screen!=='battle'))break;const card=await page.evaluate(()=>{const b=B.Flow.battle;const choices=b.piles.hand.map(c=>({uid:c.instance_id,def:B.CardById[c.card_id]})).filter(c=>c.def.cost<=b.energy);return (choices.find(c=>c.def.effects.some(e=>e.type==='damage'))||choices[0])?.uid;});if(card)await page.locator('.hand [data-instance="'+card+'"]').click();else await page.locator('#endTurn').click();}await screen('reward');}
async function nextBattle(){for(let step=0;step<10;step++){const id=await page.evaluate(()=>{const r=B.Flow.run,ids=B.Dungeon.available(r);return ids.find(id=>['battle','boss'].includes(B.Dungeon.node(r,id).room_type))||ids[0];});assert(id,'Available path');await page.locator('[data-node="'+id+'"]').click();const current=await page.evaluate(()=>B.Flow.screen);if(current==='battle')return;if(current==='event'){await page.getByRole('button',{name:'휴식 · HP +8',exact:true}).click();}else if(current==='puzzle'){await page.getByRole('button',{name:'퍼즐 건너뛰기 · 보상 없음',exact:true}).click();}}throw Error('No next battle');}
(async()=>{await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const url='http://127.0.0.1:'+server.address().port;browser=await chromium.launch({headless:true,channel:process.env.BRODUN_BROWSER_CHANNEL||'msedge'});page=await browser.newPage({viewport:{width:1280,height:900}});page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)failures.push(r.url());});
 try{
  await record('Baseline reproduces stale select-screen class and hidden stage',async()=>{await page.goto(url+'/__baseline');await page.locator('#newGame').click();await page.locator('#begin').click();assert(await page.locator('#overlay').evaluate(el=>el.classList.contains('select-screen')));await page.screenshot({path:path.join(out,'00-before.png')});await page.locator('#scene').selectOption('gallery');await page.locator('#restart').click();assert(await page.locator('#stage').isHidden());assert.equal(await page.evaluate(()=>current),'battle');});
  await page.goto(process.env.BRODUN_TEST_URL||url);
  await record('Three characters select → visible map, no stale class',async()=>{for(const hero of ['warrior','mage','priest']){await start(hero);assert.equal(await page.evaluate(()=>B.Flow.run.character_id),hero);assert.equal(await page.locator('#overlay').getAttribute('class'),'overlay map-screen');assert(await page.locator('#stage').isVisible());assert(await page.locator('#bg').evaluate(el=>el.complete&&el.naturalWidth>0));assert.equal(await page.locator('.mapnodes .node').count(),11);}});
  await start('warrior');await page.screenshot({path:path.join(out,'01-map.png')});
  await record('Only connected node enabled; illegal node rejected',async()=>{assert.equal(await page.locator('.node:not(:disabled)').count(),1);assert(await page.locator('[data-node="boss"]').isDisabled());assert.equal(await page.evaluate(()=>B.Flow.enter('boss')),false);assert.equal(await page.evaluate(()=>B.Flow.run.current_room_id),'start');});
  await page.locator('[data-node="r1"]').click();await screen('battle');await page.screenshot({path:path.join(out,'02-battle.png')});
  await record('Combat attack feedback, guard, draw, enemy turn, win → one reward',async()=>{await page.evaluate(()=>{window.qaFeedback=[];window.qaObserver=new MutationObserver(records=>{for(const record of records)for(const node of record.addedNodes)if(node.nodeType===1&&node.classList.contains('damage-pop'))window.qaFeedback.push({text:node.textContent,visible:node.getBoundingClientRect().height>0});});window.qaObserver.observe(document.getElementById('stage'),{childList:true});});await page.locator('.hand [data-card="earth_strike"]').click();await page.waitForFunction(()=>window.qaFeedback.some(e=>e.text==='-8'&&e.visible));await page.evaluate(()=>window.qaObserver.disconnect());assert.equal(await page.evaluate(()=>B.Flow.battle.enemy.hp),18);await win();assert.equal(await page.locator('.panel').count(),1);assert.equal(await page.evaluate(()=>B.Flow.run.completed_room_ids.length),0);assert.equal(await page.evaluate(()=>B.Flow.show('map')),false);});
  await page.screenshot({path:path.join(out,'03-reward.png')});
  await record('Gold +50 persists; double resolution refused; map completed',async()=>{const hp=await page.evaluate(()=>B.Flow.run.player.hp);await page.getByRole('button',{name:'골드 +50',exact:true}).click();await screen('map');assert.equal(await page.evaluate(()=>B.Flow.run.player.gold),50);assert.equal(await page.evaluate(()=>B.Flow.run.player.hp),hp);assert.match(await page.locator('#runHud').innerText(),/Gold: 50/);assert.match(await page.locator('.toast').innerText(),/\+50 Gold/);assert(await page.locator('[data-node="r1"]').evaluate(el=>el.classList.contains('done')));assert.equal(await page.locator('.node:not(:disabled)').count(),3);assert.equal(await page.evaluate(()=>B.Reward.resolve(B.Flow.run,{...B.Flow.reward,resolved:false},'gold')),false);});
  await record('Next room retains HP, gold, character and seed',async()=>{const previous=await page.evaluate(()=>({hp:B.Flow.run.player.hp,gold:B.Flow.run.player.gold,hero:B.Flow.run.character_id,seed:B.Flow.run.seed}));await nextBattle();const actual=await page.evaluate(()=>({hp:B.Flow.run.player.hp,gold:B.Flow.run.player.gold,hero:B.Flow.run.character_id,seed:B.Flow.run.seed}));assert.equal(actual.gold,previous.gold);assert.equal(actual.hero,previous.hero);assert.equal(actual.seed,previous.seed);assert(actual.hp>=previous.hp);});
  await record('Card candidates → add one → deck modal → future combat use',async()=>{await start('mage',29);await page.locator('[data-node="r1"]').click();await win();await page.getByRole('button',{name:'새 카드 획득 · 3장 중 선택',exact:true}).click();const ids=await page.locator('.card-candidates [data-card]').evaluateAll(nodes=>nodes.map(n=>n.dataset.card));assert.equal(new Set(ids).size,3);const id=ids[0];await page.screenshot({path:path.join(out,'04-card-reward.png')});await page.locator('.card-candidates [data-card="'+id+'"]').click();await screen('map');assert.equal(await page.evaluate(()=>B.Flow.run.deck.length),5);await page.locator('#deckBtn').click();assert.equal(await page.locator('#deckDialog .deck-list article').count(),5);assert(await page.locator('#deckDialog [data-card="'+id+'"]').isVisible());await page.screenshot({path:path.join(out,'05-deck.png')});await page.getByRole('button',{name:'닫기',exact:true}).click();await nextBattle();for(let i=0;i<3&&!(await page.locator('.hand [data-card="'+id+'"]').count());i++){await page.locator('#endTurn').click();await page.waitForFunction(()=>!B.Flow.battle.busy);}assert(await page.locator('.hand [data-card="'+id+'"]').count());await page.locator('.hand [data-card="'+id+'"]').click();await page.waitForFunction(()=>!B.Flow.battle.busy||B.Flow.battle.status!=='active');assert(await page.evaluate(id=>B.Flow.battle.log.some(s=>s.includes(B.CardById[id].name)),id));});
  await record('New game invalidates in-flight battle timers',async()=>{await start();await page.locator('[data-node="r1"]').click();await page.locator('.hand [data-card="earth_strike"]').click();await page.locator('#newRun').click();await page.waitForTimeout(1000);assert.equal(await page.evaluate(()=>B.Flow.screen),'select');assert.equal(await page.evaluate(()=>B.Flow.run),null);});
  await record('Skip reward grants nothing',async()=>{await start('priest');await page.locator('[data-node="r1"]').click();await win();await page.locator('#skipReward').click();await screen('map');assert.equal(await page.evaluate(()=>B.Flow.run.deck.length),4);assert.equal(await page.evaluate(()=>B.Flow.run.player.gold),0);});
  await record('Puzzle success → reward and event apply → map',async()=>{let puzzleSeed=0;while(!(await page.evaluate(seed=>B.Dungeon.generate(seed).find(n=>n.id==='r2').room_type==='puzzle',puzzleSeed)))puzzleSeed++;await start('warrior',puzzleSeed);await page.locator('[data-node="r1"]').click();await win();await page.locator('#skipReward').click();await page.locator('[data-node="r2"]').click();await screen('puzzle');for(const name of ['땅','물','불'])await page.getByRole('button',{name,exact:true}).click();await screen('reward');await page.locator('#skipReward').click();let eventSeed=0;while(!(await page.evaluate(seed=>B.Dungeon.generate(seed).find(n=>n.id==='r2').room_type==='event',eventSeed)))eventSeed++;await start('warrior',eventSeed);await page.locator('[data-node="r1"]').click();await win();await page.locator('#skipReward').click();await page.locator('[data-node="r2"]').click();await screen('event');await page.getByRole('button',{name:'주머니 줍기 · Gold +15',exact:true}).click();await screen('map');assert.equal(await page.evaluate(()=>B.Flow.run.player.gold),15);assert(await page.evaluate(()=>B.Flow.run.completed_room_ids.includes('r2')));});
  await record('Boss terminal battle → reward → run complete',async()=>{await start('warrior',17);for(let step=0;step<7;step++){await nextBattle();const boss=await page.evaluate(()=>B.Flow.run.active_room_id==='boss');await win();await page.getByRole('button',{name:'골드 +50',exact:true}).click();if(boss)break;}await screen('complete');assert.equal(await page.evaluate(()=>B.Flow.run.status),'complete');assert(await page.evaluate(()=>B.Flow.run.completed_room_ids.includes('boss')));assert.equal(await page.evaluate(()=>B.Dungeon.available(B.Flow.run).length),0);});
  await record('HP 0 → defeat → retry character choice',async()=>{await start();await page.locator('[data-node="r1"]').click();for(let i=0;i<8;i++){await page.locator('#endTurn').click();await page.waitForFunction(()=>B.Flow.screen==='defeat'||!B.Flow.battle.busy);}await screen('defeat');assert.equal(await page.evaluate(()=>B.Flow.run.player.hp),0);await page.getByRole('button',{name:'다시 시작 · 캐릭터 선택',exact:true}).click();await screen('select');});
  await record('Gallery return and filming mode preserve run',async()=>{await start();await page.locator('#galleryBtn').click();await screen('gallery');assert(await page.locator('#stage').isHidden());await page.getByRole('button',{name:'게임 화면으로 돌아가기',exact:true}).click();await screen('map');assert(await page.locator('#gallery').isHidden());await page.locator('#record').click();assert(await page.locator('body').evaluate(el=>el.classList.contains('recording')));await page.keyboard.press('Escape');assert(!await page.locator('body').evaluate(el=>el.classList.contains('recording')));});
  await record('390px mobile selection, map, battle and rewards accessible',async()=>{await page.setViewportSize({width:390,height:844});await start('priest');assert(await page.locator('#begin').isHidden());await page.screenshot({path:path.join(out,'06-mobile-map.png')});await page.locator('[data-node="r1"]').click();await page.screenshot({path:path.join(out,'07-mobile-battle.png')});await win();await page.getByRole('button',{name:'새 카드 획득 · 3장 중 선택',exact:true}).click();await page.screenshot({path:path.join(out,'08-mobile-reward.png')});await page.locator('.card-candidates .battle-card').first().click();await screen('map');assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));});
  await record('All asset requests and browser scripts error-free',async()=>{assert.deepEqual(errors,[]);assert.deepEqual(failures,[]);assert(await page.locator('#bg').evaluate(el=>el.complete&&el.naturalWidth>0));});
  fs.writeFileSync(path.join(out,'browser-results.json'),JSON.stringify({status:'PASS',tests:results,errors,failures},null,2));
 }catch(error){console.error(error);fs.writeFileSync(path.join(out,'browser-results.json'),JSON.stringify({status:'FAIL',tests:results,error:String(error),errors,failures},null,2));process.exitCode=1;}finally{await browser.close();server.close();}
})();
