const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),sandbox={Date,Math,console};sandbox.window=sandbox;vm.createContext(sandbox);
vm.runInContext(fs.readFileSync(path.join(root,'addon-manifest.js'),'utf8'),sandbox);
for(const file of ['balance','cards','run-state','dungeon','deck','reward','enemies','battle'])vm.runInContext(fs.readFileSync(path.join(root,'js',file+'.js'),'utf8'),sandbox,{filename:file});
const B=sandbox.B;let checks=0;const check=(condition,message)=>{assert(condition,message);checks++;};
for(let seed=0;seed<1000;seed++){
 const a=B.Dungeon.generate(seed),b=B.Dungeon.generate(seed);check(JSON.stringify(a)===JSON.stringify(b),'Same seed recreates graph');
 const counts=Object.fromEntries(['start','battle','puzzle','event','boss'].map(type=>[type,a.filter(n=>n.room_type===type).length]));check(JSON.stringify(counts)===JSON.stringify({start:1,battle:5,puzzle:2,event:2,boss:1}),'PRD room distribution');
 const reachable=new Set(['start']);for(const n of a){check(reachable.has(n.id),'Every node reachable');for(const id of n.next_room_ids){const m=a.find(n=>n.id===id);check(m&&m.column>n.column,'Forward edges only');reachable.add(id);}check(n.id==='boss'?n.next_room_ids.length===0:n.next_room_ids.length>0,'Only boss terminal');}
}
for(const hero of Object.keys(B.Heroes)){
 const r=B.Run.create(hero,42);check(B.Dungeon.enter(r,'boss')===null,'Locked node rejected');const room=B.Dungeon.enter(r,'r1');check(!!room,'First connected room enters');check(B.Dungeon.available(r).length===0,'Active content prevents new node');
 const battle=B.Battle.begin(r,room);check(battle.piles.hand.length===4,'Starter drawn');check(r.player.hp===B.Config.max_hp,'Battle never resets HP');
 for(let turn=0;turn<25;turn++){for(const instance of [...battle.piles.hand])B.Deck.use(battle.piles,instance.instance_id);B.Deck.endTurn(battle.piles);B.Deck.nextTurn(battle.piles);const all=['draw','hand','discard','exhaust'].flatMap(k=>battle.piles[k]);check(all.length===r.deck.length&&new Set(all.map(c=>c.instance_id)).size===r.deck.length,'Deck instance conservation');}
 r.player.hp=23;const reward=B.Reward.create(r);check(new Set(reward.candidates).size===3,'Three distinct candidates');check(!B.Reward.resolve(r,reward,'card','invalid'),'Invalid reward rejected');check(B.Reward.resolve(r,reward,'gold'),'Gold resolves');check(!B.Reward.resolve(r,reward,'gold'),'Same object duplicate blocked');check(!B.Reward.resolve(r,{...reward,resolved:false},'gold'),'Recreated duplicate blocked');check(r.player.gold===50&&r.player.hp===23,'Gold retained with HP');check(r.completed_room_ids.includes('r1')&&B.Dungeon.available(r).length===3,'Complete then unlock connected nodes');
 const next=B.Dungeon.enter(r,B.Dungeon.available(r)[0]);const second=B.Reward.create(r),id=second.candidates[0];check(B.Reward.resolve(r,second,'card',id),'Card resolves');check(r.deck.length===5&&r.acquired_cards.length===1,'Permanent deck grows');const piles=B.Deck.begin(r,next);B.Deck.draw(piles,1);check(piles.hand.some(c=>c.card_id===id),'Acquired card drawn in next battle');
 check(B.Run.spendGold(r,20)&&r.player.gold===30&&!B.Run.spendGold(r,31),'Future shop atomic spending');
}
for(const def of B.Cards){const r=B.Run.create('warrior',8),room=B.Dungeon.enter(r,'r1'),b=B.Battle.begin(r,room);r.player.hp=20;b.enemy.hp=100;b.enemy.max_hp=100;b.enemy.element=def.id==='ice_link'?'water':'fire';b.enemy.poison=3;b.block=2;B.Battle.resolveCard(r,b,def);check(b.enemy.hp>=0&&r.player.hp<=B.Config.max_hp&&b.energy<=B.Config.energy_cap,'Valid effect result '+def.id);check(def.description===B.describeEffects(def.effects),'Description derives from data');}
{const r=B.Run.create('mage',1),room=B.Dungeon.enter(r,'r1'),b=B.Battle.begin(r,room);b.enemy.hp=100;b.enemy.element='water';check(B.Battle.resolveCard(r,b,B.CardById.ice_link)===11,'Water → ice exactly one combo');b.enemy.element='fire';check(B.Battle.resolveCard(r,b,B.CardById.explosion_link)===13,'Fire → explosion exactly one combo');b.strength=2;check(B.Battle.resolveCard(r,b,B.CardById.lightning_chain)===10,'Two hits each get strength');b.enemy.hp=2;b.enemy.poison=4;check(B.Battle.poisonTick(b)===2&&b.enemy.hp===0,'Poison can kill');b.block=6;b.enemy.weak=2;check(B.Battle.enemyHit(r,b)===0&&b.enemy.weak===1,'Block and weak');}
{const r=B.Run.create('priest',7);B.Dungeon.enter(r,'r1');const reward=B.Reward.create(r);check(B.Reward.resolve(r,reward,'skip')&&r.deck.length===4&&r.player.gold===0,'Skip applies nothing');}
for(const def of Object.values(B.Enemies)){
 const r=B.Run.create('warrior',5),room={id:'r1',column:1,floor_index:1,room_type:def.rank==='boss'?'boss':'battle',encounter_type:def.rank};const b={enemy:B.Enemy.create(def,room),block:0};
 for(let turn=0;turn<12;turn++){r.player.hp=1000;b.enemy.weak=turn%3===1?2:0;b.block=turn%2?5:0;B.Enemy.decide(b);const snapshot=B.Enemy.preview(b),raw=snapshot.type==='attack'?snapshot.amount*snapshot.hits:0,beforeHP=r.player.hp,block=b.block;B.Enemy.execute(r,b,snapshot);check(beforeHP-r.player.hp===Math.max(0,raw-block),'Preview and actual match '+def.id);check(b.last_enemy_action.pattern_index===snapshot.pattern_index,'No reroll after preview');if(snapshot.type==='block')check(b.enemy.block===snapshot.amount,'Enemy block works');}
}
for(const asset of sandbox.BRODUN_ADDON_ASSETS.assets.filter(a=>a.frames)){check(asset.frames.length===20,'20 frames '+asset.id);for(const frame of asset.frames){const data=fs.readFileSync(path.join(root,'Assets/BRODUNArt',frame.file));check(data.readUInt32BE(16)===frame.width&&data.readUInt32BE(20)===frame.height,'Manifest dimensions');check([4,6].includes(data[25]),'PNG alpha');}}
console.log(JSON.stringify({result:'PASS',assertions:checks,seeds:1000,cards:B.Cards.length,heroes:3,addon_frames:180,enemies:Object.keys(B.Enemies).length}));
